"""Inward-owned ports. Vendor and infrastructure types stop at adapters."""

from collections.abc import AsyncIterator, Iterable
from typing import Protocol
from uuid import UUID

from .schemas import CanonicalEvent, Decision


class MarketDataProvider(Protocol):
    async def events(self, symbols: Iterable[str]) -> AsyncIterator[CanonicalEvent]: ...

    async def health(self) -> dict[str, object]: ...


class EventRepository(Protocol):
    def record_event(self, event: CanonicalEvent) -> None: ...
    def record_decision(self, decision: Decision) -> None: ...
    def record_sweep(self, sweep: dict[str, object]) -> None: ...
    def record_impact_cluster(self, cluster: dict[str, object]) -> None: ...
    def record_impact_session(self, session: dict[str, object]) -> None: ...
    def replay_impact_clusters(self, run_id: UUID | None = None) -> Iterable[dict[str, object]]: ...
    def replay_impact_sessions(self, run_id: UUID | None = None) -> Iterable[dict[str, object]]: ...
    def replay_sweep_transitions(
        self, run_id: UUID | None = None
    ) -> Iterable[dict[str, object]]: ...
    def replay_events(self) -> Iterable[CanonicalEvent]: ...


class Clock(Protocol):
    def now(self) -> object: ...
